function useCountryStates() {
    const fetchCountriesWithStates = async () => {
        try {
            // Return static country list instead of API call
            const countries = [
                { name: 'Afghanistan', code: 'AF', states: [] },
                { name: 'Albania', code: 'AL', states: [] },
                { name: 'Algeria', code: 'DZ', states: [] },
                { name: 'Andorra', code: 'AD', states: [] },
                { name: 'Angola', code: 'AO', states: [] },
                { name: 'Antigua and Barbuda', code: 'AG', states: [] },
                { name: 'Argentina', code: 'AR', states: [] },
                { name: 'Armenia', code: 'AM', states: [] },
                { name: 'Australia', code: 'AU', states: [] },
                { name: 'Austria', code: 'AT', states: [] },
                { name: 'Azerbaijan', code: 'AZ', states: [] },
                { name: 'Bahamas', code: 'BS', states: [] },
                { name: 'Bahrain', code: 'BH', states: [] },
                { name: 'Bangladesh', code: 'BD', states: [] },
                { name: 'Barbados', code: 'BB', states: [] },
                { name: 'Belarus', code: 'BY', states: [] },
                { name: 'Belgium', code: 'BE', states: [] },
                { name: 'Belize', code: 'BZ', states: [] },
                { name: 'Benin', code: 'BJ', states: [] },
                { name: 'Bhutan', code: 'BT', states: [] },
                { name: 'Bolivia', code: 'BO', states: [] },
                { name: 'Bosnia and Herzegovina', code: 'BA', states: [] },
                { name: 'Botswana', code: 'BW', states: [] },
                { name: 'Brazil', code: 'BR', states: [] },
                { name: 'Brunei', code: 'BN', states: [] },
                { name: 'Bulgaria', code: 'BG', states: [] },
                { name: 'Burkina Faso', code: 'BF', states: [] },
                { name: 'Burundi', code: 'BI', states: [] },
                { name: 'Cabo Verde', code: 'CV', states: [] },
                { name: 'Cambodia', code: 'KH', states: [] },
                { name: 'Cameroon', code: 'CM', states: [] },
                { name: 'Canada', code: 'CA', states: [] },
                { name: 'Central African Republic', code: 'CF', states: [] },
                { name: 'Chad', code: 'TD', states: [] },
                { name: 'Chile', code: 'CL', states: [] },
                { name: 'China', code: 'CN', states: [] },
                { name: 'Colombia', code: 'CO', states: [] },
                { name: 'Comoros', code: 'KM', states: [] },
                { name: 'Congo (Congo-Brazzaville)', code: 'CG', states: [] },
                { name: 'Congo (DRC)', code: 'CD', states: [] },
                { name: 'Costa Rica', code: 'CR', states: [] },
                { name: 'Croatia', code: 'HR', states: [] },
                { name: 'Cuba', code: 'CU', states: [] },
                { name: 'Cyprus', code: 'CY', states: [] },
                { name: 'Czechia', code: 'CZ', states: [] },
                { name: 'Denmark', code: 'DK', states: [] },
                { name: 'Djibouti', code: 'DJ', states: [] },
                { name: 'Dominica', code: 'DM', states: [] },
                { name: 'Dominican Republic', code: 'DO', states: [] },
                { name: 'Ecuador', code: 'EC', states: [] },
                { name: 'Egypt', code: 'EG', states: [] },
                { name: 'El Salvador', code: 'SV', states: [] },
                { name: 'Equatorial Guinea', code: 'GQ', states: [] },
                { name: 'Eritrea', code: 'ER', states: [] },
                { name: 'Estonia', code: 'EE', states: [] },
                { name: 'Eswatini', code: 'SZ', states: [] },
                { name: 'Ethiopia', code: 'ET', states: [] },
                { name: 'Fiji', code: 'FJ', states: [] },
                { name: 'Finland', code: 'FI', states: [] },
                { name: 'France', code: 'FR', states: [] },
                { name: 'Gabon', code: 'GA', states: [] },
                { name: 'Gambia', code: 'GM', states: [] },
                { name: 'Georgia', code: 'GE', states: [] },
                { name: 'Germany', code: 'DE', states: [] },
                { name: 'Ghana', code: 'GH', states: [] },
                { name: 'Greece', code: 'GR', states: [] },
                { name: 'Grenada', code: 'GD', states: [] },
                { name: 'Guatemala', code: 'GT', states: [] },
                { name: 'Guinea', code: 'GN', states: [] },
                { name: 'Guinea-Bissau', code: 'GW', states: [] },
                { name: 'Guyana', code: 'GY', states: [] },
                { name: 'Haiti', code: 'HT', states: [] },
                { name: 'Honduras', code: 'HN', states: [] },
                { name: 'Hungary', code: 'HU', states: [] },
                { name: 'Iceland', code: 'IS', states: [] },
                { name: 'India', code: 'IN', states: [] },
                { name: 'Indonesia', code: 'ID', states: [] },
                { name: 'Iran', code: 'IR', states: [] },
                { name: 'Iraq', code: 'IQ', states: [] },
                { name: 'Ireland', code: 'IE', states: [] },
                { name: 'Israel', code: 'IL', states: [] },
                { name: 'Italy', code: 'IT', states: [] },
                { name: 'Jamaica', code: 'JM', states: [] },
                { name: 'Japan', code: 'JP', states: [] },
                { name: 'Jordan', code: 'JO', states: [] },
                { name: 'Kazakhstan', code: 'KZ', states: [] },
                { name: 'Kenya', code: 'KE', states: [] },
                { name: 'Kiribati', code: 'KI', states: [] },
                { name: 'Kuwait', code: 'KW', states: [] },
                { name: 'Kyrgyzstan', code: 'KG', states: [] },
                { name: 'Laos', code: 'LA', states: [] },
                { name: 'Latvia', code: 'LV', states: [] },
                { name: 'Lebanon', code: 'LB', states: [] },
                { name: 'Lesotho', code: 'LS', states: [] },
                { name: 'Liberia', code: 'LR', states: [] },
                { name: 'Libya', code: 'LY', states: [] },
                { name: 'Liechtenstein', code: 'LI', states: [] },
                { name: 'Lithuania', code: 'LT', states: [] },
                { name: 'Luxembourg', code: 'LU', states: [] },
                { name: 'Madagascar', code: 'MG', states: [] },
                { name: 'Malawi', code: 'MW', states: [] },
                { name: 'Malaysia', code: 'MY', states: [] },
                { name: 'Maldives', code: 'MV', states: [] },
                { name: 'Mali', code: 'ML', states: [] },
                { name: 'Malta', code: 'MT', states: [] },
                { name: 'Marshall Islands', code: 'MH', states: [] },
                { name: 'Mauritania', code: 'MR', states: [] },
                { name: 'Mauritius', code: 'MU', states: [] },
                { name: 'Mexico', code: 'MX', states: [] },
                { name: 'Micronesia', code: 'FM', states: [] },
                { name: 'Moldova', code: 'MD', states: [] },
                { name: 'Monaco', code: 'MC', states: [] },
                { name: 'Mongolia', code: 'MN', states: [] },
                { name: 'Montenegro', code: 'ME', states: [] },
                { name: 'Morocco', code: 'MA', states: [] },
                { name: 'Mozambique', code: 'MZ', states: [] },
                { name: 'Myanmar', code: 'MM', states: [] },
                { name: 'Namibia', code: 'NA', states: [] },
                { name: 'Nauru', code: 'NR', states: [] },
                { name: 'Nepal', code: 'NP', states: [] },
                { name: 'Netherlands', code: 'NL', states: [] },
                { name: 'New Zealand', code: 'NZ', states: [] },
                { name: 'Nicaragua', code: 'NI', states: [] },
                { name: 'Niger', code: 'NE', states: [] },
                { name: 'Nigeria', code: 'NG', states: [] },
                { name: 'North Macedonia', code: 'MK', states: [] },
                { name: 'Norway', code: 'NO', states: [] },
                { name: 'Oman', code: 'OM', states: [] },
                { name: 'Pakistan', code: 'PK', states: [] },
                { name: 'Palau', code: 'PW', states: [] },
                { name: 'Panama', code: 'PA', states: [] },
                { name: 'Papua New Guinea', code: 'PG', states: [] },
                { name: 'Paraguay', code: 'PY', states: [] },
                { name: 'Peru', code: 'PE', states: [] },
                { name: 'Philippines', code: 'PH', states: [] },
                { name: 'Poland', code: 'PL', states: [] },
                { name: 'Portugal', code: 'PT', states: [] },
                { name: 'Qatar', code: 'QA', states: [] },
                { name: 'Romania', code: 'RO', states: [] },
                { name: 'Russia', code: 'RU', states: [] },
                { name: 'Rwanda', code: 'RW', states: [] },
                { name: 'Saint Kitts and Nevis', code: 'KN', states: [] },
                { name: 'Saint Lucia', code: 'LC', states: [] },
                { name: 'Saint Vincent and the Grenadines', code: 'VC', states: [] },
                { name: 'Samoa', code: 'WS', states: [] },
                { name: 'San Marino', code: 'SM', states: [] },
                { name: 'Sao Tome and Principe', code: 'ST', states: [] },
                { name: 'Saudi Arabia', code: 'SA', states: [] },
                { name: 'Senegal', code: 'SN', states: [] },
                { name: 'Serbia', code: 'RS', states: [] },
                { name: 'Seychelles', code: 'SC', states: [] },
                { name: 'Sierra Leone', code: 'SL', states: [] },
                { name: 'Singapore', code: 'SG', states: [] },
                { name: 'Slovakia', code: 'SK', states: [] },
                { name: 'Slovenia', code: 'SI', states: [] },
                { name: 'Solomon Islands', code: 'SB', states: [] },
                { name: 'Somalia', code: 'SO', states: [] },
                { name: 'South Africa', code: 'ZA', states: [] },
                { name: 'South Korea', code: 'KR', states: [] },
                { name: 'South Sudan', code: 'SS', states: [] },
                { name: 'Spain', code: 'ES', states: [] },
                { name: 'Sri Lanka', code: 'LK', states: [] },
                { name: 'Sudan', code: 'SD', states: [] },
                { name: 'Suriname', code: 'SR', states: [] },
                { name: 'Sweden', code: 'SE', states: [] },
                { name: 'Switzerland', code: 'CH', states: [] },
                { name: 'Syria', code: 'SY', states: [] },
                { name: 'Taiwan', code: 'TW', states: [] },
                { name: 'Tajikistan', code: 'TJ', states: [] },
                { name: 'Tanzania', code: 'TZ', states: [] },
                { name: 'Thailand', code: 'TH', states: [] },
                { name: 'Timor-Leste', code: 'TL', states: [] },
                { name: 'Togo', code: 'TG', states: [] },
                { name: 'Tonga', code: 'TO', states: [] },
                { name: 'Trinidad and Tobago', code: 'TT', states: [] },
                { name: 'Tunisia', code: 'TN', states: [] },
                { name: 'Turkey', code: 'TR', states: [] },
                { name: 'Turkmenistan', code: 'TM', states: [] },
                { name: 'Tuvalu', code: 'TV', states: [] },
                { name: 'Uganda', code: 'UG', states: [] },
                { name: 'Ukraine', code: 'UA', states: [] },
                { name: 'United Arab Emirates', code: 'AE', states: [] },
                { name: 'United Kingdom', code: 'GB', states: [] },
                { name: 'United States', code: 'US', states: [] },
                { name: 'Uruguay', code: 'UY', states: [] },
                { name: 'Uzbekistan', code: 'UZ', states: [] },
                { name: 'Vanuatu', code: 'VU', states: [] },
                { name: 'Vatican City', code: 'VA', states: [] },
                { name: 'Venezuela', code: 'VE', states: [] },
                { name: 'Vietnam', code: 'VN', states: [] },
                { name: 'Yemen', code: 'YE', states: [] },
                { name: 'Zambia', code: 'ZM', states: [] },
                { name: 'Zimbabwe', code: 'ZW', states: [] }
            ];

            // Sort alphabetically by name (already sorted, but keeping for safety)
            return countries.sort((a, b) => a.name.localeCompare(b.name));

        } catch (error) {
            console.error('Error fetching countries:', error);
            return [];
        }
    };
    
    return fetchCountriesWithStates;
}

export default useCountryStates;